name: Python API DevOps Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 main.py

  delivery:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/python-api-devops .

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/python-api-devops
